pipeline 
{
agent
{
docker 
{
image 'python:2.7.16-slim'
}
}
stages
{
stage("build")
{
when
{
changeset "**/vote/**"
}
steps
{
echo 'Build vote app'
dir('vote')
{
sh 'pip install -i requirements.txt'
}
}
}
stage("test")
{
when
{
changeset "**/vote/**"
}
steps
{
echo 'Running Tests on vote app'
dir('vote')
{
sh 'nosetests -v'
}
}
}
}
post
{
always
{
echo 'Building multibranch pipeline for result iscompleted..'
}
}
}
